### ISSUE TITLE
Renaming a Pc object causes it to no longer be able to find its certificate

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#107]
Could be fixed in several ways:
- the certificate name should be stored in an other (invisible in admin) field of the model upon first creation of the model.
- prevent Pc names to be changed.
- rename the certificate along with the model.
- create a fresh certificate with the new name (and remove/invalidate previous one?)

**Comment by davidfokkema** [comment]
What was the use case? Did this actually come up?

**Comment by 153957** [comment]
It happened. I think Bob 'recycled' the Pc (and Station) for Station number 97 for an Auger test station.

**Comment by davidfokkema** [comment]
Ah, here be dragons. Since it *was* a new pc, and creating a new pc entry worked, I'm all for preventing names from being changed.

**Comment by 153957** [comment]
Are certificates being revoked when a Pc object is deleted? I don't think so, especially since the server might be unable to find the certificate if it has been renamed. I'm ok with preventing renames, but we should add certificate revoking (if not yet implemented).

**Comment by davidfokkema** [comment]
Alas, revoking certificates must be done manually. As in, logging onto the server and deleting the file, and then reloading the vpn server. Maybe even restart, to make sure the connection is broken. We never tested that.

**Comment by 153957** [comment]
Can't that be added to the 'delete' method of the Pc model? Calling an xmlrpc method on the VPN server to delete the key, just like proxy.create_key... That may be a lot of work, and will require some testing..

**Comment by davidfokkema** [comment]
Yes, it can. It is indeed some work, and we'll probably (almost) never need it. Maybe a short document describing the manual procedure is enough. It will almost certainly take a *lot* less time. However, that makes it possible to delete a Pc object, and forget about the certificate. I think I'm OK with the manual procedure and the warning, especially considering time constraints.

**Comment by 153957** [comment]
Indeed, it would not be a bad idea to do a manual cleanup of old certificates that currently exist. First check if those that we would expect to be there are there, and then find the ones that should no longer be there.

**Comment by davidfokkema** [comment]
+1

**Comment by 153957** [comment]
Get list of expected certificate names in Django shell:
```
from django_publicdb.inforecords.models import Pc
[pc.name for pc in Pc.objects.filter(type__slug='client')]
```

**Comment by davidfokkema** [comment]
Well, at the time I was sure certificates were checked by seeing if a .crt file matched. Now, I think we can remove all client certificates from the server and the clients would *still* be able to connect. Simply because the server would see that the certificate presented by the client was signed by our own CA. Damn. I really did *not* understand our authentication procedures.

**Comment by 153957** [comment]
Is there a different way in which we can revoke certificates?

**Comment by tomkooij** [comment]
Certificates are immutable. Revoke means *add to blacklist*. 

If we just store the certificate in the public database we can add the certificate to the blacklist (manually or automatic) whenever we remove a pc object, or it key get's compromised.

There is indeed no need for copying keys to `tietar`. 

In a perfect world we would:
Store the root CA secret key on `pique` and let the STATION PC generate an RSA keypair and send it's certificate signing request (CSR) to an admin, while keeping it's secret key secret. An admin uses the admin interface on pique to create a PC object, and uploades the CSR to create a certificate signed with the root CA and stores the certificate (or just it's serial) in the database, to be able to revoke it. Keys are not in possession of the admins or on pique or tietar.  `hisparcvpnd` is  only used to add the new hostname to the hostfile on `tietar`. The admin then sends the certificate to the station pc, which can login because it owns the matching secret key.

**Comment by davidfokkema** [comment]
I don't like to live in your perfect world, 😜.

**Comment by 153957** [comment]
No longer relevant with #323
