### ISSUE TITLE
Tietar needs a few fixes

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/publicdb#118]
Just a few, for now:
- [x] enlarge /proc/sys/net/netfilter/nf_conntrack_max?
- [x] limit nagios.log?
- [x] fix resolv.conf, must point to localhost, always

**Comment by 153957** [comment]
There seems to be something wrong with nsca.
@NorbertvanVeen reported that the HiSPARC Monitor shows "Send_ncsa_command failed".
Some Science Park stations 'crashed' because of full RAM due to ~2000 send_nsca processes running.
After (or rather while) killing the Monitor the numbers did drop.. Perhaps the nsca processes kept piling up while tietar was down?
However, tietar is running now, so is the nsca service, but still most stations in the network have failed passive checks (which use nsca).

![send_nsca](https://cloud.githubusercontent.com/assets/1433682/13111468/3dec05c4-d586-11e5-9d77-851a547e9fd1.png)

**Comment by davidfokkema** [comment]
That is some broken implementation! I hate Nagios.

**Comment by davidfokkema** [comment]
Btw, thanks, @NorbertvanVeen !

**Comment by 153957** [comment]
![nscaerror](https://cloud.githubusercontent.com/assets/1433682/13189748/978c7ac6-d759-11e5-9ba8-814e398ebfc3.png)

Currently stations seem to 'nicely' fail to submit passive checks.

**Comment by davidfokkema** [comment]
Done!
