### ISSUE TITLE
Disallow (some?) special characters for station passwords

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#164]
Recently a new startion has issues uploading data because it used a password containing `&`, which was communicated to the datastore as `&amp;`, causing it to not recognise the password on the station. This could perhaps be fixed by fixing how that config for the datastore is generated, but it would be safer to simply prevent such characters from being used. Perhaps only allow alphanumeric characters..

**Comment by tomkooij** [comment]
Interesting.  I though you were referring to the stations passing data by HTTP POST, but It seems you are referring to: `/databases/frome/station_list.csv` which indeed has a password encoded in the HTML/XML (incorrect) way.  Because it was passed to the server by XML-RPC and not properly decoded. [src](https://github.com/HiSPARC/publicdb/blob/master/scripts/fake-datastore-xmlrpc-server.py)

Fixing that encoding should be much easier than disallowing special characters, which is an odd thing to do for passwords anyway.
