### ISSUE TITLE
Error with new IPAddressFields

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#186]
It appears Pcs can no longer be updated.

```
Internal Server Error: /admin/inforecords/pc/184/change/

ProgrammingError at /admin/inforecords/pc/184/change/
operator does not exist: character = inet
LINE 1: ...ROM "inforecords_pc" WHERE ("inforecords_pc"."ip" = '194.171...
                                                            ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

See df08f8dc80147d86578fe811aa8d33846104840b, 8b17b7157a737b653f973c48a90974f2170b0036, and dda833282aa8efca3b3724596b090d2a61246773 for recent changes.

**Comment by kaspervd** [comment]
This is because postgreSQL is strongly typed. I'll try to find out how to cast inforecords_pc.ip to a string and fix this.

**Comment by 153957** [comment]
This can be fixed by adding a migration to:
- add a new GenericIPAddressField to the model
- copy the ip address to the new field
- remove the old field
- rename the new field to the original name.

**Comment by kaspervd** [comment]
What ip address do you suggest to move to the new field? Pc.ip already is a GenericIPAddressField.

**Comment by kaspervd** [comment]
The migration suggested by Arne seems to resolve the problem (see https://github.com/HiSPARC/publicdb/commit/26ffca755e97ba041a984b1ac06e3155d8c3444f). 

However, I'm not able to verify this in my publicdb-VM since i get a "Connection timed out" error when django tries to send something to the vpn-VM upon recreating the problem. I'm able to reach the vpn-VM from the publicdb-VM. Does anyone have a suggestion on how to verify the fix?

**Comment by kaspervd** [comment]
I assume that this has to do with my own VM setup and I will apply the new migration on the live server.

**Comment by kaspervd** [comment]
This problem seems to be resolved.
