### ISSUE TITLE
Station layouts broken (at least on data.hisparc.nl)

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/publicdb#223]
http://data.hisparc.nl/show/stations/501/config/

No station layout rendered.

**Comment by 153957** [comment]
That is because the template `layout_canvas` was renamed to `canvas`.

This broke: `{% include "layout_canvas.html" %}`

See: eeafdf89649b544df6fd6c7358318cb95f7b3efc

It was updated in some templates, but not in `station_config.html`
https://github.com/HiSPARC/publicdb/blob/master/publicdb/status_display/templates/station_config.html#L152

**Comment by tomkooij** [comment]
Ok. I'll fix it.

**Comment by 153957** [comment]
Thanks, sorry for missing that one :)

**Comment by tomkooij** [comment]
Reopened: Only two detectors shown. Have not investigated yet.

**Comment by 153957** [comment]
Indeed, I saw the same yesterday.
I was already worried that you guys restructured that stations 😉

**Comment by 153957** [comment]
Fixed in 7e75b00efdaf028fd855f4a6755380365b7450b7
