### ISSUE TITLE
Change status on data.hisparc.nl

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#231]
Currently the status icons on data.hisparc.nl reflect the Nagios reported status, which is 'down' for most stations because of the VPN issues. This does not properly reflect the data acquisition status of the stations. Perhaps the icons should be changed to something like this:

- green - 'had data yesterday' (either any data at all, or specifically in the last hour of the day)
- yellow - 'no data yesterday or bad config'
- red - 'no recent data, or no configurations'

**Comment by davidfokkema** [comment]
+1. I was thinking of that as well, but didn't have time to do anything about it. On the bright side, I'm entertaining the thought of spending Monday working on HiSPARC stuff. Here's hoping regular work doesn't interfere...

**Comment by renaldo20** [comment]
I could not agree more.
David and I seriously considered the same suggestion about half a year ago.
‘Somebody’ from Englang was supposed to tackle the NAGIOS-issues, but sofar nothing has happened. As far as I know.

The core of the suggestion is to change the status icons from expressing the NAGIOS monitoring status to expressing the most recent data acquisition status.
Perfect!

For the past couple of months I have been reporting on a daily basis about the status of the 10 stations at Science Parc, recently expanded to 12 stations. The status of data acquisition that is.
This was a manual attempt with the intention of supporting the effort by Kasper and Bob to get all the stations at Science Parc in working order again. As a starting point for the rest of the HiSPARC stations we agreed to tackle Science Parc first. And to support the effort with a manual daily status report regarding the data acquisition.
I will discontinu this daily reporting shortly and would very much welcome an automated version with status icons representing the data acquisition status

Of the 10 daily reported stations, now only one station (#509 UvA2) is not transferring data since 22/5 due to networking problems.
3 of the remaing 9 stations still have NAGIOS status red, so there is no possibility for remote maintenance. All maintenance involves a physical visit to the computer of these stations.
Of the 2 added stations, 1 is delivering data already, but the other station is work-in-progress.

My 5 cents,
Reno Beekman

**Comment by 153957** [comment]
Mostly done in #235. Could still use improvements to the Station status pages.
These currently only show Nagios status information but could be improved with more data-based status.

**Comment by 153957** [comment]
What might also be useful is a page with stations grouped by status.

http://data.hisparc.nl/show/stations_by_country/
http://data.hisparc.nl/show/stations_by_name/
http://data.hisparc.nl/show/stations_by_number/

So a new:
http://data.hisparc.nl/show/stations_by_status/

Where the stations could be grouped based on their status (and sorted by number within the group)

**Comment by davidfokkema** [comment]
Working on @153957's last suggestion in #236.

**Comment by 153957** [comment]
Last thing to do would be to make station status pages more useful: http://data.hisparc.nl/show/stations/4/status/

**Comment by tomkooij** [comment]
Status station is now determined by "station has Summary" (https://github.com/HiSPARC/publicdb/blob/master/publicdb/status_display/status.py#L23)

This results in stations being "up" if we only recieve weather station data:
https://data.hisparc.nl/show/stations/602/2019/3/5/
On this day "station 602" was UP while it was actually down.

Fix: check for "number_events > .." in the query linked above.

**Comment by 153957** [comment]
Add `num_events__isnull=False`
